web_chat/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('login/', views.login_page,name='login'),
    path('registration/', views.registration_page, name='registration'),
    path('logout/', views.logout_user, name='logout'),

]

web_chat/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('home/', views.index,name='index'),
    path('chat/<room_id>/', views.room, name='room'),
    path('create_chat/', views.create_chat, name='create_chat'),
    path('delete_chat/<room_id>/', views.delete_chat, name='delete_chat'),
    path('add_to_room/<room_id>/', views.add_to_room, name='add_to_room'),

]

web_chat/web_chat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
    path('',include('account.urls'))
    
]

web_chat/account/models.py
from django.db import models

# Create your models here.

web_chat/chat/models.py
from django.db import models
from django.contrib.auth.models import User

class Room(models.Model):
    name = models.CharField(max_length=25)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return f'Chat: {self.name}'


class Participants(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)

    def __str__(self):
        return f'User: {self.user}, room: {self.room}'


class Message(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    msg_text = models.CharField(max_length=255, verbose_name='Message text')
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'In chat: {self.room} {self.user} write {self.msg_text} '

web_chat/account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class RegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control form-control-lg',
               'name': 'username', 'placeholder': 'Username', }
    ))

    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control form-control-lg', 'type': 'password',
               'name': 'password1', 'placeholder': 'Password', }
    ))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control form-control-lg', 'type': 'password',
               'name': 'password2', 'placeholder': 'Repeat password', }
    ))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control form-control-lg',
                    'placeholder': 'Email'
                }
            ),
        }

web_chat/account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from .forms import RegistrationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def login_page(request):

    if request.user.is_authenticated:
        return redirect ('/home/')

    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username,password=password)

        if user is not None:
            login(request, user=user)
            return redirect('/home/')
        else:
            messages.info(request, 'Username or password is incorrect')

    return render(request,'account/login.html')

def registration_page(request):
    form = RegistrationForm()
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()

            username = request.POST.get('username')
            password = request.POST.get('password1')
            user = authenticate(request, username=username,password=password)
            login(request, user=user)
            return redirect('/home/')
        
            
    context = {
        'form' : form,
    }
    return render(request,'account/registration.html', context)

@login_required(login_url='/login/')
def logout_user(request):
    logout(request)
    return redirect('/login/')

web_chat/chat/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404 , render, redirect
from .models import Room, Participants, Message, User
from django.contrib.auth.decorators import login_required
from channels.db import database_sync_to_async

def index(request):

    if request.user.is_authenticated:
        context = user_rooms(request)
        return render(request, 'base.html', context)

    context = {
        'rooms': []
    }
    return render(request, 'base.html', context)


@login_required(login_url='/login/')
def room(request, room_id):

    if get_object_or_none(Participants, room=room_id, user=request.user) is None:
        return redirect ('/login/')

    room_messages = Message.objects.filter(room=room_id)
    
    context = {
        'room_id': room_id,
        'user_name': request.user.username,
        'room_messages' : room_messages,
    }

    context |= user_rooms(request)
    return render(request, 'chat/room.html', context)


@login_required(login_url='/login/')
def create_chat(request):

    if request.POST:
        user = User.objects.get(username=request.user)
        all_user_rooms = user_rooms(request)
        room_name = request.POST.get('room_name')

        if not is_room_exist(room_name, all_user_rooms['rooms']):
            room = Room(name=room_name, owner=user)
            room.save()
            Participants(user=user, room=room).save()

            return redirect(f'/chat/{room.id}/')
        else:
            messages.info(request, 'You already have a chat with this name')

    context = user_rooms(request)

    return render(request, 'chat/create_room.html', context)

@login_required(login_url='/login/')
def delete_chat(request, room_id):
    
    Participants.objects.filter(room = room_id, user = request.user).delete()

    return redirect('/home/')

def is_room_exist(room_name, room_list):
    for room in room_list:
        if room_name == room.name:
            return True

    return False

def add_to_room(request,room_id):
    
    if request.POST:
        username = request.POST.get('username')
        user = get_object_or_none(User,username=username)
        print(user)
        if user is not None:
            room = Room.objects.get(pk=room_id)

            if get_object_or_none(Participants,user=user,room=room) is None:
                Participants(user=user,room=room).save()

                return redirect (f'/chat/{room_id}/')
            else:
                messages.info(request,'This user is already in the room')
        else:
            messages.info(request,'No such user exists')

    context = {
        'room_id' : room_id,
    }
    context |= user_rooms(request)

    return render(request, 'chat/add_user.html', context)

def user_rooms(request):
    participants = Participants.objects.filter(user=request.user)
    rooms = []
    for i in participants:
        rooms.append(Room.objects.get(id=i.room.id))

    context = {
        'rooms': rooms
    }

    return context

def get_object_or_none(model, **kwargs):
    try:
        obj = model.objects.get(**kwargs)
    except model.DoesNotExist:
        return None
    return obj 

@database_sync_to_async
def leave_message(user_name, room_name, message):
    user = User.objects.get(username=user_name)
    room = Room.objects.get(id=room_name)
    Message(user=user, room=room, msg_text=message).save()

web_chat/chat/templates/base.html
<!DOCTYPE html>
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Chat{% endblock title %}</title>
</head>
<div class="row">
    <div class="col-3">
        <div class="d-flex flex-column flex-shrink-0 p-3 bg-light">

            {% if request.user.is_authenticated %}
            <div class="row">
                <div class="col">
                    <span class="fs-4 ms-2">Chat</span>
                </div>
                <div class="col">
                    <div class="d-flex justify-content-end">
                        <div class="dropdown">
                            <a href="#" class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle"
                                id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg src="" fill="black" alt="" width="32" height="32" class="rounded-circle me-2"></svg>
                                <strong>{{request.user}}</strong>
                            </a>
                            <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
                                <li>
                                    <a class="dropdown-item" href="{% url 'chat:create_chat' %}">New chat</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'account:logout' %}">Sign out</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            {% include 'chat/room_list.html' %}
            {% else %}


            <ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item mb-1">
                    <a href="{% url 'account:login' %}" class="nav-link active">
                        <svg class="bi me-2" width="16" height="16">
                            <use xlink:href="#home"></use>
                        </svg>
                        Login
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'account:registration' %}" class="nav-link active">
                        <svg class="bi me-2" width="16" height="16">
                            <use xlink:href="#home"></use>
                        </svg>
                        Sign Up
                    </a>
                </li>
            </ul>
        </div>
        {% endif %}
    </div>
</div>

<div class="col-7">
    {% block content %}

    {% endblock content %}
</div>
</div>

</body>

</html>

web_chat/chat/templates/chat/add_user.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'chat:add_to_room' room_id %}" method="POST" class="form">
    {% csrf_token %}
        <input type="text" name="username" class="form-control form-control-lg" placeholder="Username"/>
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
    {% if messages %}
            {% for message in messages %}
                <p class="alert alert-danger" role="alert">{{message}}</p>
            {% endfor %}
    {% endif %}
{% endblock content %}

web_chat/chat/templates/chat/create_room.html
{% extends 'base.html' %}


{% block content %}
    <form action="{% url 'chat:create_chat' %}" method="POST" class="form">
        {% csrf_token %}
        <div class="card mt-5">
            <div class="card-body p-3">
            
            <div class="form-outline mb-4">
                <input type="text" name="room_name" class="form-control form-control-lg" placeholder="Chat name"/>
            </div>
            
            {% if messages %}
                {% for message in messages %}
                    <p class="alert alert-danger" role="alert">{{message}}</p>
                {% endfor %}
            {% endif %}
            <div class="d-flex justify-content-end">
                <button class="btn btn-success">Create</button>
            </div>
            </div>
        </div>
    </form>
{% endblock content %}

web_chat/chat/templates/chat/index.html
{% extends 'base.html' %}

{% block content %}
 What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
{% endblock content %}

web_chat/chat/templates/chat/room.html
{% extends 'base.html' %}

{% block content %}
    <div class="d-flex justify-content-center">
        <div class="card w-100">
            <div class="card-body">

                <div class="message-content">
                    <div id="chat-log">
                        {% for message in room_messages %}
                            {% if message.user == request.user %}
                                <div class='text-end'>
                                {{message.msg_text}}
                                <p class='small text-muted'>At {{message.pub_date}}</p>
                                </div>
                            {% else %}
                                <div class='text-start'>
                                {{message.msg_text}}
                                <p class='small text-muted'>At {{message.pub_date}}</p>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <div class="d-flex w-100">
                    <input id="chat-message-input" type="text" class="w-100"><br>
                    <input id="chat-message-submit" type="button" class="btn btn-primary ms-2" value="Send">
                    <a href="{% url 'chat:add_to_room' room_id %}" class="btn btn-warning">Add</a>
                </div>

            </div>
        </div>
    </div>

    {% comment %} <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send"> {% endcomment %}
    {{ room_id|json_script:"room-id" }}
    {{ user_name|json_script:"user-name" }}
    <script>
        const roomId = JSON.parse(document.getElementById('room-id').textContent);
        const userName = JSON.parse(document.getElementById('user-name').textContent);
        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomId
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            add_html(data)
        };

        function add_html(data){
            text = ''
            
            if (data.username == userName){
                text =  "<div class='text-end'>"+
                data.message+
                "<p class='small text-muted'>"+"At "+ data.time + "</p>"+
                "</div>"
                ;
            }
            else{
                text =  "<div class='text-start'>"+
                data.message+
                "<p class='small text-muted'>"+"From "+data.username+" at "+ data.time + "</p>"+
                "</div>"
                ;
            } 
            document.querySelector('#chat-log').innerHTML  += text
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            const  months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
            const currentdate = new Date();
            var year = currentdate.getFullYear();
            var month = currentdate.getMonth();
            var day = currentdate.getDate()
            var hour = currentdate.getUTCHours() - 12;
            var minut = currentdate.getMinutes();

            var time = months[month] + " " + day + ", " + year + ', ' + hour + ':' + minut;

            if (currentdate.getHours()<=12){
                time += " a.m."
            }
            else{
                time += " p.m."
            }

            if (message != ''){
                chatSocket.send(JSON.stringify({
                    'message': message,
                    'username' : userName,
                    'time' : time,
                }));
            }
            messageInputDom.value = '';
        };
    </script>

{% endblock content %}

web_chat/chat/templates/chat/room_list.html
<hr />
<ul class="nav nav-pills flex-column mb-auto">
    <div
      class="bg-light"
      
    >
      {% for room in rooms %}
      <li class="nav-item">
        <div class="row w-100">
            <div class="col-8">
              <div class="d-flex justify-content-start">
                <a href="{% url 'chat:room' room.id %}" class="nav-link link-dark ">
                  {{room.name}}
                </a>
              </div>
            </div>
            <div class="col-2">
              <div class="d-flex justify-content-end">
                <a href="{% url 'chat:delete_chat' room.id %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="25" height="40" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                  </svg>
                </a>
              </div>
          </div>
        </div>
      </li>
      {% endfor %}
    </div>
</ul>